### PR TITLE
Slight fix to the fix for #1

### PR DESCRIPTION
**Pull request by finlay**
Hi 

Your fixlength was applied before splitting. I have switched the order: 
   1. convert base64 to base64url encoding
   2. split on .
   3. fix length of pieces  (actually only need to fix length for one of those pieces.

F

### CODE REVIEW

**Comment by simonh1000** [comment]
Hi, did you spot anything technically wrong with my current code, otherwise I will merge these changes with my next release, whenever that might be

**Comment by finlay** [comment]
Hi Simon

Yeah, there was a problem with your implementation. The 1.0.1 version is currently broken, as far as I can tell. The problem is due to the fact that the JWT token is three base64url encoded chunks, separated by dots. So you need to split before fixing the length.

I think a new released to fix 1.0.1 would be a good idea. In the meantime I am pulling it from my fork.

**Comment by simonh1000** [comment]
Thanks. I'm merging it

**Comment by simonh1000** [comment]
And deployed with a new Phoenix example - thanks so much

**Comment by finlay** [comment]
Great, Ill pull into my project now.

F

**Pull request merged**
